### ISSUE TITLE
Compute tables for lookup-by-tag

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-transformation#10]
Compute two tables supporting lookup of addresses / clusters by tag. Proposed schema:

address_by_tag
|- tagPrefix (first three tag characters)
|- tagPrefix5 (first five tag characters) - if needed
|- tag (lowercase; removed whitespace and interpunction)
|- address (explicitly tagged address)

cluster_by_tag (same as above, cluster instead of address)

**Comment by defconst** [comment]
https://github.com/graphsense/graphsense-tagpacks/commit/6640614600c51def03305f2e8797572d4689ecbb
