### ISSUE TITLE
Memory utilization

### ISSUE THREAD

**Issue by ridicoulous** [graphsense/graphsense-transformation#13]
Something strange with RAM. I have a lot of warnings about memory:
![image](https://user-images.githubusercontent.com/5917631/56638123-f3436d80-6675-11e9-8fb6-b46ca9b743d6.png)
I'm setted up it to 52gb at `submit.sh`:
![image](https://user-images.githubusercontent.com/5917631/56638143-00f8f300-6676-11e9-842e-ab045d452653.png)
But looks like it does not take memory size from configs, cause memory used only 12 GB from 60GB available
![image](https://user-images.githubusercontent.com/5917631/56638155-09e9c480-6676-11e9-9afb-75662fe0ed9a.png)
Any ideas?

**Comment by behas** [comment]
the transformation pipelines is designed to run on a computing cluster with several strong high-memory machines

**Comment by ridicoulous** [comment]
> the transformation pipelines is designed to run on a computing cluster with several strong high-memory machines

Could you please provide me a minimal configuration for cluster?

**Comment by behas** [comment]
We have not yet tested a minimal config. Here you see what we are using: https://github.com/graphsense/graphsense.github.io/wiki/GraphSense-FAQ

**Comment by ridicoulous** [comment]
Thank you. Strange, didn't see this topic
