### ISSUE TITLE
Writing table job is stop

### ISSUE THREAD

**Issue by HyungJiny** [graphsense/graphsense-transformation#17]
Hello.

I try to setup in my laptop to use.
But it has some issue that is stop working when I do `./submit`.

![image](https://user-images.githubusercontent.com/11986878/61030869-52a15600-a3f9-11e9-9b9a-ceaeafb08ee0.png)
![image](https://user-images.githubusercontent.com/11986878/61030984-909e7a00-a3f9-11e9-817b-073184c2874b.png)
I checked spark job at http://localhost:4040/jobs but this job still running.
But it can't writing computed transaction data in cassandra table.

I'm setted my labtop.
 - spark 2.4.3
 - openjdk version 1.8.0_212
 - sbt 1.2.8
 - cassandra 3.11.4

Any ideas? I want know how to solve this problem.
Thanks.

**Comment by behas** [comment]
see #13
