### ISSUE TITLE
ZEC exchange rate issue

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-transformation#18]
ZEC Txid: t1P9CEYDzUFpKkqjWGdbCeQBFt2z7aoLxHU

the zcash amount should be roughly 4.26 EUR and not 490.

**Comment by behas** [comment]
will be fixed by graphsense/graphsense-blocksci#3

**Comment by defconst** [comment]
Fixed 
![Dashboard Screenshot](https://i.imgur.com/nsmXa7J.png)
