### ISSUE TITLE
Use address int IDs instead of address byte arrays

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-transformation#21]
Compute an int ID for each address right at the beginning of the transformation. Store that ID as "internal_id" in the address table. Use that ID throughout the subsequent steps (cluster ID = min address ID; relation src and dst are IDs; maybe in mod X buckets)

**Comment by defconst** [comment]
Added in 1a669492c6569c340d7de2b7f5d924c8c9076dc7
