### ISSUE TITLE
Address Total received in EUR does not match incoming_relations total received

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-transformation#25]
Example:

1MYVnbz9BecBihQcXtMA7rnDxVKUWdH52Z shows total received of 111.5

1DkRtM5BJ48Gi45uF9whJrKnPqpkz7EyB is an outgoing node of that address; when listing incoming address relations, it shows above address with total received of 111.5

However, when switching to EUR, the values don't match anymore: 649,387 vs. 961,751.8

It seems that there is sth wrong with the conversion.

**Comment by defconst** [comment]
Fixed in https://github.com/graphsense/graphsense-transformation/commit/91ab5727221a56a19f11f4d283dc7b88000e0fd8
