### ISSUE TITLE
Always fill the tx_list field in cluster_outgoing_relations

### ISSUE THREAD

**Issue by MatteoRomiti** [graphsense/graphsense-transformation#33]
Currently in the table `cluster_outgoing_relations`, the field `tx_list` is not empty only if there are less than N = 100 txs between two clusters. Usually, GraphSense users, especially in the dashboard, need as few as one tx to have proof that two clusters are linked and not N. 

I'd suggest having this field always filled with at least one tx hash. The maximum number of listed txs could also be limited to 1.

**Comment by defconst** [comment]
Implemented in REST API
