### ISSUE TITLE
cluster_addresses: eliminate unused fields

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-transformation#52]
The dashboard display:
- Address
- First usage
- Last usage
- Balance
- Received

Therefore, cluster_addresses can be reduced to (@myrho please confirm):

CREATE TABLE cluster_addresses (
    cluster_group int,
    cluster int,
    address_id int,
    first_tx_timestamp int,
    last_tx_timestamp int
    total_received FROZEN <value>,
    total_spent FROZEN <value>,
    PRIMARY KEY (cluster_group, cluster, address_id)
);

**Comment by myrho** [comment]
Rest interface actually just uses `address_id` and retrieves address rows from `address_by_id_group` in a second lookup.

**Comment by myrho** [comment]
Proposed changes:
* Table `address`: 
  * Make `address_id`, `address_group_id` primary key
  * Remove `address_prefix`
* Add lookup table instead:
```
CREATE TABLE address_ids_by_address_prefix (
    address_prefix text,
    address blob,
    address_id int,
    PRIMARY KEY (address_prefix, address)
);
```
* Remove `address_by_id_group`
* Remove all fields from `cluster_addresses` except the primary key fields.
