### ISSUE TITLE
Spark versions do not match

### ISSUE THREAD

**Issue by goldforg** [graphsense/graphsense-transformation#62]
In documentation there is written 
>> Download, install, and run Apache Spark (version 3.1.2) in $SPARK_HOME:

But in Dockerfile there is refered to the old spark library.
>> https://www.apache.org/dist/spark/spark-2.4.7/spark-2.4.7-bin-without-hadoop-scala-2.12.tgz

Error:
>> java.io.InvalidClassException: org.apache.spark.deploy.ApplicationDescription; local class incompatible: stream classdesc serialVersionUID = 6543101073799644159, local class serialVersionUID = 1574364215946805297

**Comment by defconst** [comment]
Fixed in develop 0316272
