### ISSUE TITLE
Unable to build transformation module

### ISSUE THREAD

**Issue by goldforg** [graphsense/graphsense-transformation#64]
There is a successful connection between cassandra and spark, except when I run transformation module, I get error something like this.

>>22/01/24 19:56:15 WARN pool.ChannelPool: [s0|/127.0.0.1:9042]  Error while opening new channel (ConnectionInitException: [s0|connecting...] Protocol initialization request, step 1 (STARTUP {CQL_VERSION=3.0.0, DRIVER_NAME=DataStax Java driver for Apache Cassandra(R), DRIVER_VERSION=4.12.0, CLIENT_ID=38b21e12-df5e-4e9c-946c-8af072094bf2, APPLICATION_NAME=Spark-Cassandra-Connector-app-20220124205608-0006}): failed to send request (com.datastax.oss.driver.shaded.netty.channel.StacklessClosedChannelException))

What could be a problem?
Thanks in advance!

**Comment by defconst** [comment]
do you run it on a single machine or a cluster? if on a cluster 127.0.0.1:9042 seems to be wrong

**Comment by goldforg** [comment]
> do you run it on a single machine or a cluster? do you use Docker or not? if on a cluster 127.0.0.1:9042 seems to be wrong

Yes you are right.
I changed in every cassandra worker rpc_address from localhost to 192...
But I still get this weird error:
>>22/01/28 15:32:09 WARN pool.ChannelPool: [s0|/192.168.66.153:9042]  Error while opening new channel (ConnectionInitException: [s0|connecting...] Protocol initialization request, step 1 (STARTUP {CQL_VERSION=3.0.0, DRIVER_NAME=DataStax Java driver for Apache Cassandra(R), DRIVER_VERSION=4.12.0, CLIENT_ID=17778d71-cdc9-407e-a326-8261d5cc3c25, APPLICATION_NAME=Spark-Cassandra-Connector-app-20220128163203-0009}): failed to send request (com.datastax.oss.driver.shaded.netty.channel.StacklessClosedChannelException))

Is there anything else I could try?

**Comment by defconst** [comment]
Can you connect to Cassandra with `cqlsh`?
