### ISSUE TITLE
Possible transaction timestamp conflict

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-transformation#67]
There are some time inconsistencies between the timestamps in graphsense and in blockchain.info explorer.

For example, the timestamp of btc transaction 4947fa293ac65914637c4bc909f13d81b0bb8194ce412cf846dd295260f24307

is 1650520243 ( 2022 13:50:43  GMT+8) in graphsense but 2022-04-21 13:46 GMT+8 in blockchain.info explorer.

Why is that the case? Can / should we fix it?

**Comment by soad003** [comment]
my quick guess is that you looked at the received time of the transaction, which I think is the time when the tx hit the mempool. Graphsense uses the block-time so the time when the transaction was included in a block. If you look at the block in blockchain.info (https://www.blockchain.com/btc/block/732810) the timestamps are identical.
