### ISSUE TITLE
Help with Spark Cassandra Join ClassCastException

### ISSUE THREAD

**Issue by yaz1** [graphsense/graphsense-transformation#69]
I am getting an error in the Transformation.scala in the computeExchangeRates method when joining the blockDate table with the 
exchangeRates, see below.

`blocksDate.join(exchangeRates, Seq(F.date), "left")`

The error message is:
`Exception in thread "main" java.lang.ClassCastException: scala.Tuple8 cannot be cast to scala.Tuple7 at org.apache.spark.sql.cassandra.execution.CassandraDirectJoinStrategy.apply(CassandraDirectJoinStrategy.scala:27)
`

It seems to be a problem with my setup as the sbt test works fine. I am using cassandra v3.11.13 and Spark 3.3.0. Your help is greatly appreciated

**Comment by defconst** [comment]
The DataStax Spark Cassandra Connector has no official support for Spark 3.3.0 at the moment, see https://github.com/datastax/spark-cassandra-connector#version-compatibility



Connector | Spark | Cassandra | Cassandra Java Driver | Minimum Java Version | Supported Scala Versions
-- | -- | -- | -- | -- | --
3.2 | 3.2 | 2.1.5*, 2.2, 3.x, 4.0 | 4.13 | 8 | 2.12
3.1 | 3.1 | 2.1.5*, 2.2, 3.x, 4.0 | 4.12 | 8 | 2.12
3.0 | 3.0 | 2.1.5*, 2.2, 3.x, 4.0 | 4.12 | 8 | 2.12

**Comment by yaz1** [comment]
Thank you, indeed this was the problem. It works now after downgrading to spark 3.2.
