### ISSUE TITLE
Transformation job  Size exceeds Integer.MAX_VALUE

### ISSUE THREAD

**Issue by imadmoussa1** [graphsense/graphsense-transformation#7]
Hello ,
While i am running the transformation job `rdd at TransformationJob.scala:92` using the submit.sh i got this error :
`ERROR Executor: Exception in task 37460.0 in stage 1.0 (TID 37464)
java.lang.IllegalArgumentException: Size exceeds Integer.MAX_VALUE`

I'm running Cassandra 3.11 and Spark 2.2.2 under Scala 2.11.8 in Ubuntu 18.04 Server.
Any clue?

**Comment by eliesoueidy** [comment]
I'm seeing the same issue with a similar setup. Tried with different job sizes (here https://github.com/graphsense/graphsense-transformation/blob/a778f2a1b44e207dfa0f3059caef657d4a015279/src/main/scala/at/ac/ait/TransformationJob.scala#L80) even with very large numbers (100,000) but still got the same problem.

This project is great btw!

**Comment by defconst** [comment]
I have this in my submit script:
```
--conf spark.sql.shuffle.partitions=500
--conf spark.default.parallelism=500 
```

**Comment by behas** [comment]
this should be solved with the most recent Spark version
