### ISSUE TITLE
Updating the feature/incremental_update Branch

### ISSUE THREAD

**Issue by yaz1** [graphsense/graphsense-transformation#70]
The current `feature/incremental_update` branch is behind and does not match the latest transformation schema.   I am considering to work on the branch and update it. Are there any fundamental issues that prevented maintaining it?

**Comment by behas** [comment]
We are currently implementing incremental update differently in another repo. We expect to publish it as part of r.22.11 (Nov.).

@defconst @soad003 plz delete deprecated branches.
