### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by imadmoussa1** [graphsense/graphsense-transformation#8]
Hello,
I am trying to run the project on my mac book ( CPU intel core i7, and  Memory 16gb )
But i have many issue, first i got out of memory error, and after fixing this problem , my disk is full .

What is the hardware requirements to run the project ?

Thank you .

**Comment by defconst** [comment]
See [FAQ](https://github.com/graphsense/graphsense.github.io/wiki/GraphSense-FAQ#what-are-the-hardware-requirements-for-graphsense)
